
# tap repositories and their packages

# Other Homebrew packages
brew 'autoconf'
brew 'brew-file'
brew 'docker'
brew 'gettext'
brew 'gist'
brew 'git'
brew 'gradle'
brew 'heroku'
brew 'heroku-node'
brew 'icu4c'
brew 'jenv'
brew 'mas'
brew 'ncurses'
brew 'openssl'
brew 'pcre'
brew 'pcre2'
brew 'pkg-config'
brew 'postgresql'
brew 'rbenv'
brew 'rbenv-gemset'
brew 'readline'
brew 'ruby-build'
brew 'zsh'

# Other Cask applications
cask 'astah-professional'
cask 'azure-data-studio'
cask 'chromedriver'
cask 'db-browser-for-sqlite'
cask 'docker'
cask 'drawio'
cask 'dropbox'
cask 'eclipse-ide'
cask 'evernote'
cask 'google-chrome'
cask 'google-drive-file-stream'
cask 'java'
cask 'sequel-pro-nightly'
cask 'slack'
cask 'springtoolsuite'
cask 'visual-studio-code'
cask 'xmind'
