
# tap repositories and their packages

tap 'homebrew/core'
brew 'anyenv'
brew 'aom'
brew 'autoconf'
brew 'awscli'
brew 'boost'
brew 'cairo'
brew 'docker'
brew 'docker-clean'
brew 'ffmpeg'
brew 'flac'
brew 'fontconfig'
brew 'freetype'
brew 'frei0r'
brew 'fribidi'
brew 'fswatch'
brew 'gdbm'
brew 'gettext'
brew 'giflib'
brew 'gist'
brew 'git'
brew 'glib'
brew 'gmp'
brew 'gnutls'
brew 'graphite2'
brew 'harfbuzz'
brew 'icu4c'
brew 'jpeg'
brew 'lame'
brew 'leptonica'
brew 'libass'
brew 'libbluray'
brew 'libevent'
brew 'libffi'
brew 'libidn2'
brew 'libogg'
brew 'libpng'
brew 'libsamplerate'
brew 'libsndfile'
brew 'libsoxr'
brew 'libtasn1'
brew 'libtiff'
brew 'libunistring'
brew 'libvidstab'
brew 'libvorbis'
brew 'libvpx'
brew 'little-cms2'
brew 'lzo'
brew 'mas'
brew 'ncurses'
brew 'nettle'
brew 'node'
brew 'opencore-amr'
brew 'openjpeg'
brew 'openssl@1.1'
brew 'opus'
brew 'p11-kit'
brew 'pcre'
brew 'pcre2'
brew 'pixman'
brew 'pkg-config'
brew 'python'
brew 'python@3.8'
brew 'rbenv'
brew 'rbenv-gemset'
brew 'readline'
brew 'rtmpdump'
brew 'rubberband'
brew 'ruby-build'
brew 'sdl2'
brew 'snappy'
brew 'source-highlight'
brew 'speex'
brew 'sqlite'
brew 'terraform'
brew 'tesseract'
brew 'theora'
brew 'tree'
brew 'unbound'
brew 'unison'
brew 'webp'
brew 'x264'
brew 'x265'
brew 'xvid'
brew 'xz'
brew 'yarn'
brew 'zsh'

tap 'homebrew/bundle'

tap 'homebrew/cask-versions'
cask 'sequel-pro-nightly'

tap 'homebrew/cask'
cask 'background-music'
cask 'chromedriver'
cask 'db-browser-for-sqlite'
cask 'docker'
cask 'drawio'
cask 'evernote'
cask 'google-chrome'
cask 'iterm2'
cask 'notable'
cask 'skype'
cask 'slack'
cask 'visual-studio-code'

tap 'caskroom/cask'

tap 'heroku/brew'
brew 'heroku'
brew 'heroku-node'

tap 'rcmdnk/file'
brew 'brew-file'

# Other Homebrew packages
brew 'openssl'

# App Store applications
mas 'com.apple.dt.Xcode', id: id:
mas 'jp.naver.line.mac', id: id:
