#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^Alacritty$" manage=off
yabai -m rule --add app="^Ghostty$" manage=off
yabai -m rule --add app="^WezTerm$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^LINE$" manage=off
yabai -m rule --add app="^1Password$" manage=off grid=10:10:3:3:3:3
yabai -m rule --add app="^ChatGPT$" manage=off
yabai -m rule --add app="^Alcove$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Chromium$" manage=off
yabai -m rule --add app="^Nani$" manage=off

yabai -m rule --add app='(^System Preferences$|^システム設定$)' manage=off
yabai -m rule --add app='^時計$' manage=off
yabai -m rule --add app='(^Terminal$|^ターミナル$)' manage=off

yabai -m rule --add app="^Notion$" space=2
yabai -m rule --add app="^Spotify$" space=3
yabai -m rule --add app="^Code$" space=4
yabai -m rule --add app="^Notion Calendar$" space=5
yabai -m rule --add app="^Slack$" space=6
yabai -m rule --add app="^Arc$" space=7
yabai -m rule --add app="^Linear$" space=8
yabai -m rule --add app="^Postman$" space=9
yabai -m rule --add app="^TablePlus$" space=10

echo "yabai configuration loaded.."
