format = """
$time$directory$golang$nodejs$python$dart$rust$deno$ruby$cmd_duration
$character"""

right_format = """
$git_status$git_branch"""

[time]
disabled = false
format = "[ $time]($style) "
style = 'bold cyan'

[directory]
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "
style = 'bold yellow'
read_only_style = 'bold red'
home_symbol = ' ~'
truncation_length = 0

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "  "
disabled = false

[git_status]
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = 'bold cyan'

# languages
[golang]
format = "[$symbol($version )]($style)"
symbol = "ﳑ "

[nodejs]
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol($version )]($style)"

[dart]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[ruby]
format = "[$symbol($version )]($style)"

[character]
success_symbol = "[-❯](bold green)"
error_symbol = "[-❯](bold red)"
