[theme]
name = "one-dark"

[ui]
agent_panel_sort = "spaces"

[keys]
focus_pane_left  = ["prefix+h", "prefix+ctrl+h"]
focus_pane_down  = ["prefix+j", "prefix+ctrl+j"]
focus_pane_up    = ["prefix+k", "prefix+ctrl+k"]
focus_pane_right = ["prefix+l", "prefix+ctrl+l"]

open_worktree = "prefix+ctrl+o"

navigate_workspace_up = "k"
navigate_workspace_down = "j"

[[keys.command]]
key = "prefix+u"
type = "popup"
command = "~/.local/bin/herdr-urlview"
description = "Open URL view"

[[keys.command]]
key = "prefix+d"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"
description = "Toggle reviewr"

[experimental]
switch_ascii_input_source_in_prefix = true
