format = """
$time$directory$cmd_duration$fill$git_status$git_branch
$character"""

command_timeout = 600

[time]
disabled = false
format = "[ $time]($style) "
style = 'bold cyan'

[fill]
symbol = " "

[directory]
format = "[ ]($style)[$path]($style)[$read_only]($read_only_style) "
style = 'bold yellow'
read_only_style = 'bold red'
truncation_length = 0

[git_branch]
format = "[$symbol$branch]($style) "
symbol = "  "
disabled = false
# truncation_length = 20
truncation_symbol = '…/'

[git_status]
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = 'bold cyan'

[character]
success_symbol = "[-❯](bold green)"
error_symbol = "[-❯](bold red)"

# languages
[golang]
disabled = true
format = "[$symbol($version )]($style)"
symbol = " "

[nodejs]
disabled = true
format = "[$symbol($version )]($style)"

[python]
disabled = true
format = "[$symbol($version )]($style)"

[dart]
disabled = true
format = "[$symbol($version )]($style)"

[rust]
disabled = true
format = "[$symbol($version )]($style)"

[deno]
disabled = true
format = "[$symbol($version )]($style)"

[ruby]
disabled = true
format = "[$symbol($version )]($style)"

[bun]
disabled = true
format = "[$symbol($version )]($style)"
symbol = " "
