# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'github/copilot.vim'

# color theme
[[plugins]]
repo = 'joshdick/onedark.vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'APZelos/blamer.nvim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# explorer
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'folke/which-key.nvim'

# syntax
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# [[plugins]]
# repo = 'prettier/vim-prettier'

# deno
# [[plugins]]
# repo = 'vim-denops/denops.vim'

# snippets
[[plugins]]
repo = 'SirVer/ultisnips'

# fuzzy finder
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# font
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

# lsp
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'

[[plugins]]
repo = 'nvim-lua/lsp-status.nvim'

# auto completion
[[plugins]]
repo = 'hrsh7th/nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-path'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'

# testings
[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

# development
[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

# statusline
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
