[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'prettier/vim-prettier'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'folke/which-key.nvim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'APZelos/blamer.nvim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
hook_add = '''
  " Hide signcolumn.
  let g:lsp_diagnostics_signs_enabled = 0
'''
hook_post_source = '''
  " Highlight LSP warnings strongly (like errors)
  highlight link LspWarningHighlight Error
'''

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
