##############################################################################
# typescript
##############################################################################
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'

##############################################################################
# vue
##############################################################################
[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

##############################################################################
# yaml
##############################################################################
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

##############################################################################
# toml
##############################################################################
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

