##############################################################################
# typescript
##############################################################################
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact', 'typescriptreact.tsx', 'vue']

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript', 'typescript.tsx', 'typescriptreact', 'typescriptreact.tsx', 'vue']

##############################################################################
# vue
##############################################################################
[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'albanm/vuetify-vim'
on_ft = ['vue']

##############################################################################
# golang
##############################################################################
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']

##############################################################################
# document
##############################################################################
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown', 'md']

##############################################################################
# development
##############################################################################
[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
depends = ['nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
depends = ['nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-path'
depends = ['nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
depends = ['nvim-cmp']

[[plugins]]
repo = 'quangnguyen30192/cmp-nvim-ultisnips'
depends = ['nvim-cmp', 'ultisnips']

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'rafamadriz/friendly-snippets'
