[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'prettier/vim-prettier'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'folke/which-key.nvim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
