[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'prettier/vim-prettier'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'folke/which-key.nvim'

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'nvim-treesitter/telescope.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope-symbols.nvim'
